### ISSUE TITLE
Site navigation

### ISSUE THREAD

**Issue by BowieRC** [BowieRC/Support-your-local#6]
Site nav

**Comment by BowieRC** [comment]
We've lost browser navigation through the back arrows supplied by the browser. I'm not sure where, I'll have to have a proper look through the code, but it is important that we get this back. I know there is navigation through the UI, but not being able to use the browser default navigation will lose people

**Comment by AmyLloyd** [comment]
I've fixed this bug and added a pull request with improved code.
